//create html element that will be injectted to page
let span = "<span class='geforce-button vr_supported'>GeforceNow</span>";

const gameTitles = [
  "41 Hours",
  "428: Shibuya Scramble",
  "7 Days to Die",
  "A-Train: All Aboard! Tourism",
  "Absolute Drift: Zen Edition",
  "Absolver",
  "Ageless",
  "Age of Conan: Unchained",
  "Age of Darkness: Final Stand",
  "Age of Wonders: Planetfall",
  "Age of Wonders III",
  "AI: The Somnium Files",
  "Alan Wake's American Nightmare",
  "Alan Wake's American Nightmare",
  "Alan Wake",
  "Alan Wake",
  "Alan Wake Remastered",
  "Albion Online",
  "Alchemist Adventure",
  "Amazing Cultivation Simulator",
  "American Fugitive",
  "American Truck Simulator",
  "AMID EVIL",
  "Amnesia: A Machine for Pigs",
  "Amnesia: A Machine for Pigs",
  "Amnesia: Rebirth",
  "Amnesia: Rebirth",
  "Amnesia: The Dark Descent",
  "Among Us",
  "Among Us",
  "The Anacrusis",
  "Anno 1404 History Edition",
  "Anno 1800",
  "Anno 1800",
  "Anno 1800",
  "Anno 2070",
  "Anno 2070",
  "Anno 2205",
  "Anno 2205",
  "AO Tennis 2",
  "Apex Legends™",
  "Apex Legends™",
  "Apollo 11 Lunar Landing Demo",
  "Aragami",
  "Aragami 2",
  "Araha: Curse of Yieun Island",
  "Arcana Heart 3 LOVEMAX SIXSTARS!!!!!! XTEND",
  "The Architect Paris",
  "Argo",
  "Arid",
  "Arise: A Simple Story",
  "ARK: Survival Evolved",
  "ARK: Survival Evolved",
  "ARK: Survival Of The Fittest",
  "Arma 2: Operation Arrowhead",
  "Arma 3",
  "Armello",
  "Armored Warfare",
  "Aron's Adventure",
  "Artifact",
  "art of rally",
  "art of rally",
  "Ashes of the Singularity: Escalation",
  "Assassin's Creed™: Director's Cut Edition",
  "Assassin's Creed™: Director's Cut Edition",
  "Assassin's Creed™: Director's Cut Edition",
  "Assassin's Creed II",
  "Assassin's Creed II",
  "Assassin's Creed Brotherhood",
  "Assassin's Creed Brotherhood",
  "Assassin's Creed Revelations",
  "Assassin's Creed Revelations",
  "Assassin's Creed III Remastered",
  "Assassin's Creed III Remastered",
  "Assassin's Creed III Remastered",
  "Assassin's Creed IV Black Flag™",
  "Assassin's Creed IV Black Flag™",
  "Assassin's Creed IV Black Flag™ - Gold Edition",
  "Assassin's Creed Rogue",
  "Assassin's Creed Rogue",
  "Assassin's Creed Rogue",
  "Assassin's Creed Unity",
  "Assassin's Creed Unity",
  "Assassin's Creed Unity",
  "Assassin's Creed: Syndicate",
  "Assassin's Creed: Syndicate",
  "Assassin's Creed: Syndicate",
  "Assassin's Creed Origins",
  "Assassin's Creed Origins",
  "Assassin's Creed Origins",
  "Assassin's Creed Odyssey",
  "Assassin's Creed Odyssey",
  "Assassin's Creed Odyssey",
  "Assassin's Creed: Valhalla",
  "Assassin's Creed: Valhalla",
  "Assassin's Creed Freedom Cry",
  "Assassin's Creed Chronicles: China",
  "Assassin's Creed Chronicles: India",
  "Assassin's Creed Chronicles: Russia",
  "Assassin's Creed III",
  "Assassin's Creed: Syndicate Gold Edition",
  "Assassin's Creed III Deluxe Edition",
  "Assetto Corsa",
  "Assetto Corsa Competizione",
  "Asterix & Obelix XXL 3 - The Crystal Menhir",
  "ASTRONEER",
  "ATLAS",
  "ATOMEGA™",
  "ATOM RPG",
  "ATOM RPG Trudograd",
  "A-Train PC Classic",
  "Automachef",
  "Automation - The Car Company Tycoon Game",
  "Autonauts",
  "Marvel's Avengers",
  "Aven Colony",
  "Aven Colony",
  "AVICII Invector",
  "Avorion",
  "AWAY: The Survival Series",
  "The Awesome Adventures of Captain Spirit",
  "Axilon: Legend of Artifacts - Prologue",
  "A Plague Tale: Innocence",
  "A Story About My Uncle",
  "Backbone",
  "Backbone",
  "Bad North: Jotunn Edition",
  "Bad North: Jotunn Edition",
  "Banners of Ruin",
  "Banners of Ruin",
  "BATTALION 1944",
  "BattleBeasts",
  "Battlefield™ 1: Revolution",
  "Battlefield™ 1: Revolution",
  "Battlefield 4™ Premium Edition",
  "Battlefield 4™ Premium Edition",
  "Battlefield™ V: Definitive",
  "Battlefield™ V: Definitive",
  "Battlefleet Gothic: Armada",
  "Battlefleet Gothic: Armada 2",
  "Battlestar Galactica Deadlock™",
  "Battletech",
  "Battlezone: Combat Commander",
  "Battle Chasers: Nightwar",
  "BeamNG.drive",
  "Beat Cop",
  "Bee Simulator",
  "Before We Leave",
  "Before We Leave",
  "Beholder",
  "Beholder 2",
  "Besiege",
  "Beyond Contact",
  "Beyond Good and Evil™",
  "Beyond Good and Evil™",
  "BIOMUTANT",
  "BIOMUTANT",
  "BLACKSAD: Under the Skin",
  "Blacksmith Legends",
  "Black Book",
  "Black Book",
  "Black Desert",
  "Black Future '88",
  "Black Mesa",
  "Black Skylands",
  "Black Skylands",
  "Black Squad",
  "Blair Witch",
  "Blair Witch",
  "Blasphemous",
  "BlazBlue: Cross Tag Battle",
  "Blightbound",
  "Blood Bowl: Legendary Edition",
  "Blood Bowl 2",
  "Blood of Steel",
  "Blue Fire",
  "Bomber Crew",
  "Boundless",
  "The Bradwell Conspiracy",
  "Brawlhalla",
  "Breathedge",
  "Breathedge",
  "Bridge Constructor Portal™",
  "Bridge Constructor: The Walking Dead",
  "Bridge Constructor: The Walking Dead",
  "Bright Memory",
  "Bright Memory: Infinite",
  "Bullet Girls Phantasi",
  "The Bus",
  "BUSTAFELLOWS",
  "Bus Simulator 18",
  "Bus Simulator 21",
  "Cake Bash",
  "Caliber",
  "Call of Cthulhu",
  "Call of Juarez Gunslinger",
  "Call of the Sea",
  "Call to Arms",
  "Call to Arms - Gates of Hell: Ostfront",
  "Cardaclysm",
  "Car Mechanic Simulator 2015",
  "Car Mechanic Simulator 2018",
  "Car Mechanic Simulator 2021",
  "Car Trader Simulator",
  "Castle Flipper",
  "Caves of Qud",
  "Cepheus Protocol",
  "Check vs Mate",
  "Chernobylite",
  "Chernobylite",
  "Chess Ultra",
  "Children of Morta",
  "Child of Light™",
  "Chinese Paladin: Sword and Fairy",
  "Chinese Parents",
  "Chivalry: Medieval Warfare",
  "Chivalry 2",
  "Chorus - Epic Games Store",
  "Chorus - Steam",
  "Chronicon",
  "Citadel: Forged with Fire",
  "Cities: Skylines©",
  "Cities: Skylines©",
  "City of Gangsters",
  "Claybook",
  "Clid the Snail",
  "Clid the Snail - Steam",
  "Cloudpunk",
  "Clustertruck",
  "Combat Mission Cold War",
  "Commandos 2 - HD Remaster",
  "Company of Crime",
  "Conan Exiles",
  "Conan Unconquered",
  "Conception PLUS: Maidens of the Twelve Stars",
  "Conglomerate 451",
  "Construction Simulator 2 US - Pocket Edition",
  "Construction Simulator 2015",
  "Control",
  "Control",
  "Control Ultimate Edition",
  "Core™",
  "The Council - Episode 1",
  "Counter-Strike",
  "Counter-Strike: Condition Zero",
  "Counter-Strike: Source",
  "Counter-Strike: Global Offensive",
  "The Crackpet Show",
  "Creativerse",
  "Creative Destruction",
  "The Crew™",
  "The Crew™",
  "The Crew 2",
  "The Crew 2",
  "The Crew 2",
  "Cris Tales",
  "Cris Tales",
  "Crossfire",
  "Crossout",
  "Crowfall",
  "Crown Trick",
  "CRSED: F.O.A.D.",
  "CRSED: F.O.A.D.",
  "Crusader Kings II",
  "Crusader Kings III",
  "Crysis 2 Remastered",
  "Crysis 3 Remastered",
  "Crysis Remastered",
  "Crysis Remastered",
  "Cube World",
  "Cultist Simulator",
  "Cuphead",
  "Curious Expedition 2",
  "Curse of the Dead Gods",
  "Curse of the Dead Gods",
  "Cyberpunk 2077",
  "Cyberpunk 2077",
  "Cyberpunk 2077",
  "CyberTaxi",
  "Cyber Hook",
  "The Cycle",
  "DAEMON X MACHINA",
  "DAEMON X MACHINA",
  "Dakar 18",
  "Danganronpa: Trigger Happy Havoc",
  "Danganronpa 2: Goodbye Despair",
  "Danganronpa V3: Killing Harmony",
  "Danganronpa Another Episode: Ultra Despair Girls",
  "Danger Scavenger",
  "DARIUSBURST Chronicle Saviours",
  "Darkest Hour: A Hearts of Iron Game",
  "Darksburg",
  "Darksiders: Warmastered Edition",
  "Darksiders: Warmastered Edition",
  "Darksiders II Deathinitive Edition",
  "Darksiders II Deathinitive Edition",
  "Darksiders III",
  "DARKSIDERS: GENESIS",
  "The Dark Crystal: Age of Resistance Tactics",
  "Darwin Project",
  "Dauntless",
  "Dawn of Man",
  "Days of War: Definitive Edition",
  "DayZ",
  "Day of Infamy",
  "DCL - The Game",
  "Deadliest Catch: The Game",
  "Deadside",
  "Dead Age",
  "Dead Age 2",
  "Dead by Daylight",
  "Dead by Daylight",
  "Dead Cells",
  "Dead Cells",
  "Dead In Vinland",
  "Dead Island Definitive Edition",
  "Dead Island: Riptide Definitive Edition",
  "Death's Door",
  "Death's Door",
  "Deathsmiles",
  "Death Rally",
  "DEATH STRANDING",
  "DEATH STRANDING",
  "Death Trash",
  "Deceit",
  "Deepest Chamber",
  "Deepest Chamber",
  "Deep Rock Galactic",
  "Deep Sky Derelicts",
  "Deliver Us The Moon: Fortuna",
  "Depth",
  "Descenders",
  "Desperados III",
  "Destiny 2",
  "Deus Ex: Human Revolution - Director's Cut",
  "Deus Ex: Mankind Divided™",
  "Deus Ex: The Fall",
  "Devil Slayer - Raksasi",
  "Dicey Dungeons",
  "Dice Legacy",
  "Dice Legacy",
  "Diplomacy is Not an Option",
  "Diplomacy is Not an Option",
  "Dirty Bomb",
  "Disciples: Liberation",
  "Disciples: Liberation",
  "Disco Elysium",
  "Disco Elysium",
  "Disgaea 2 PC",
  "Disgaea 4 Complete+",
  "Disgaea 5 Complete",
  "Disgaea PC",
  "Distance",
  "Divinity: Original Sin (Classic)",
  "Divinity: Original Sin - Enhanced Edition",
  "Divinity: Original Sin 2 - Definitive Edition",
  "Tom Clancy's The Division™",
  "Tom Clancy's The Division™",
  "Tom Clancy's The Division 2",
  "Tom Clancy's The Division 2",
  "DoDonPachi Resurrectio",
  "Don't Starve",
  "Don't Starve Together",
  "Door Kickers",
  "Door Kickers: Action Squad",
  "Door Kickers 2: Task Force North",
  "Dorfromantik",
  "Dota 2",
  "Dota Underlords",
  "Do Not Feed the Monkeys",
  "Dragon Age™: Inquisition - Game of the Year Edition",
  "Dragon Age™: Inquisition - Game of the Year Edition",
  "Dreadlands",
  "Dreamscaper",
  "Dreamscaper",
  "Driftland: The Magic Revival",
  "Drone Swarm",
  "Drug Dealer Simulator",
  "Dual Universe",
  "Dungeons 3",
  "Dungeons 3",
  "Dungeon Defenders",
  "Dungeon Defenders II",
  "Dungeon Defenders: Awakened",
  "The Dungeon Of Naheulbeuk: The Amulet Of Chaos",
  "The Dungeon Of Naheulbeuk: The Amulet Of Chaos",
  "Dungeon of the Endless™ - Crystal Edition",
  "Dungeon Siege",
  "Dungreed",
  "DUSK",
  "Dusk Diver",
  "Dwarrows",
  "Dying Light",
  "Dying Light 2 Stay Human",
  "Dying Light 2 Stay Human",
  "Dying Light: Bad Blood",
  "DYSMANTLE",
  "Dyson Sphere Program",
  "Earth 2160",
  "EARTH DEFENSE FORCE: WORLD BROTHERS",
  "EARTH DEFENSE FORCE 4.1 The Shadow of New Despair",
  "EARTH DEFENSE FORCE 4.1 WINGDIVER THE SHOOTER",
  "EARTH DEFENSE FORCE 5",
  "EARTH DEFENSE FORCE: IRON RAIN™",
  "Eastward",
  "Edge Of Eternity",
  "Edge Of Eternity",
  "Eldest Souls",
  "ELEX",
  "ELEX 2",
  "Elite Dangerous",
  "Elite Dangerous",
  "ELYON",
  "Empire of Angels IV",
  "Empire of Sin",
  "Empyrion - Galactic Survival",
  "Encased",
  "Encased: A Sci-Fi Post-Apocalyptic RPG - Steam",
  "Enclave",
  "Endless Legend™ - Emperor Edition",
  "Endless Space - Collection",
  "Endless Space 2 - Digital Deluxe Edition",
  "Endless World Idle RPG",
  "Endzone - A World Apart",
  "Enlisted",
  "Enter the Gungeon",
  "Enter the Gungeon",
  "Epic Chef - Steam",
  "Epistory - Typing Chronicles",
  "Escape from Naraka",
  "Escape Simulator",
  "The Escapists",
  "The Escapists 2",
  "The Eternal Cylinder",
  "Eternal Return",
  "Europa Universalis III Complete",
  "Europa Universalis IV",
  "Europa Universalis IV",
  "Euro Truck Simulator 2",
  "Everreach: Project Eden",
  "EVERSPACE™",
  "EVERSPACE™ 2",
  "EVE Online",
  "EVE Online",
  "EVE Online",
  "Evil Genius",
  "Evil Genius 2: World Domination",
  "Evoland Legendary Edition",
  "Exanima",
  "Expeditions: Rome - Epic Games Store",
  "Expeditions: Rome - Steam",
  "Expeditions: Viking",
  "F.I.S.T.: Forged In Shadow Torch",
  "Factorio",
  "Fade to Silence",
  "The Falconeer",
  "Fantasy General II",
  "FAR: Changing Tides",
  "Faraday Protocol",
  "Farming Simulator 15",
  "Farming Simulator 17",
  "Farming Simulator 19",
  "Farming Simulator 19",
  "Farming Simulator 22 - Epic Games Store",
  "Farming Simulator 22 - Steam",
  "Farm Manager 2018",
  "Farm Together",
  "Far Cry",
  "Far Cry",
  "Far Cry 2: Fortune's Edition",
  "Far Cry 2: Fortune's Edition",
  "Far Cry 2: Fortune's Edition",
  "Far Cry 3",
  "Far Cry 3: Blood Dragon",
  "Far Cry 3: Blood Dragon",
  "Far Cry 3 Deluxe Edition",
  "Far Cry 3",
  "Far Cry 3 Deluxe Edition",
  "Far Cry Primal",
  "Far Cry Primal",
  "Far Cry Primal",
  "Far Cry 4",
  "Far Cry 4",
  "Far Cry 4",
  "Far Cry New Dawn",
  "Far Cry New Dawn",
  "Far Cry New Dawn",
  "Far Cry 5",
  "Far Cry 5",
  "Far Cry 5",
  "Far Cry 6",
  "Fate Seeker",
  "Fate Seeker II (天命奇御二)",
  "Fear The Wolves",
  "FIA European Truck Racing Championship",
  "The Final Station",
  "Firewatch",
  "Fire Pro Wrestling World",
  "The Fisherman - Fishing Planet",
  "Fishing: Barents Sea",
  "The Flame in the Flood",
  "Fly Corp",
  "FORECLOSED",
  "FORECLOSED",
  "The Forest",
  "FOREWARNED",
  "Forged Battalion",
  "The Forgotten City",
  "The Forgotten City",
  "Fortnite",
  "Forts",
  "For Honor™",
  "For Honor™",
  "For Honor™",
  "For The King",
  "For The King",
  "Foundation",
  "Friday the 13th: The Game",
  "FrostPunk",
  "FrostPunk",
  "FTL: Faster Than Light",
  "FTL: Faster Than Light",
  "Furi",
  "Galactic Civilizations 3 - Epic Games Store",
  "Galactic Civilizations 3 - Steam",
  "Gamedec",
  "Gamedec",
  "Garfield Kart - Furious Racing",
  "Garry's Mod",
  "Gas Station Simulator",
  "Generation Zero",
  "Genesis Alpha One Deluxe Edition",
  "Ghostrunner",
  "Ghostrunner Demo",
  "Ghostrunner",
  "Tom Clancy's Ghost Recon Breakpoint",
  "Tom Clancy's Ghost Recon Wildlands",
  "Gloomhaven",
  "Goat Simulator",
  "God's Trigger",
  "Gods Will Fall",
  "Gods Will Fall",
  "Going Medieval",
  "Going Medieval",
  "Going Under",
  "Golf Club: Wasteland",
  "Golf With Your Friends",
  "Gone Home",
  "GONNER2",
  "GoNNER",
  "GoNNER",
  "Gothic 3",
  "Granado Espada",
  "Granblue Fantasy: Versus",
  "Gravel",
  "GRAVEN",
  "GRAVEN",
  "Greak: Memories of Azur",
  "GreedFall",
  "Green Hell",
  "Griftlands",
  "GRIME",
  "Grim Dawn",
  "GRIP: Combat Racing",
  "Groove Coaster",
  "GTFO",
  "The Guild II: Renaissance",
  "The Guild 3",
  "Guild Wars 2",
  "GUILTY GEAR -STRIVE-",
  "GUILTY GEAR Xrd -SIGN-",
  "GUILTY GEAR Xrd -REVELATOR-",
  "GUILTY GEAR XX ACCENT CORE PLUS R",
  "Gujian3",
  "Gunfire Reborn",
  "GWENT: The Witcher Card Game",
  "Hacknet",
  "Hakuoki: Kyoto Winds",
  "Half-Life",
  "Half-Life 2",
  "Half-Life 2: Deathmatch",
  "Half-Life 2: Episode Two",
  "Hammerting",
  "Hammerting",
  "Hardspace: Shipbreaker",
  "Haven - Steam",
  "Headsnatchers",
  "Hearts of Iron II: Complete",
  "Hearts of Iron IV",
  "Hellish Quart",
  "Hello Neighbor",
  "Hello Neighbor",
  "Hello Neighbor: Hide and Seek",
  "Hello Neighbor: Hide and Seek",
  "Hellpoint",
  "Hellpoint",
  "Hell Let Loose",
  "Heroes & Generals",
  "Heroes & Generals",
  "Heroes of Might & Magic® III - HD Edition",
  "Heroes of Might & Magic V",
  "Heroes of Might & Magic V: Tribes of the East",
  "Heroes of Might & Magic V: Tribes of the East",
  "Heroes of Might & Magic V",
  "Heroes of the Three Kingdoms 8",
  "Hextech Mayhem: A League of Legends Story™",
  "Hextech Mayhem: A League of Legends Story™",
  "Hide and Shriek™",
  "Hitman 2: Silent Assassin",
  "HITMAN 3",
  "Hitman: Blood Money",
  "Hitman: Absolution™",
  "HITMAN™",
  "HITMAN™",
  "HITMAN™2",
  "HITMAN 3",
  "Hobo: Tough Life",
  "Hokko Life",
  "Holdfast: Nations At War",
  "Hollow Knight",
  "Homefront: The Revolution",
  "Home Behind 2",
  "Honey, I Joined a Cult",
  "Hood: Outlaws & Legends",
  "Hood: Outlaws & Legends",
  "Hotshot Racing",
  "HOT WHEELS UNLEASHED™",
  "HOT WHEELS UNLEASHED™",
  "House Flipper",
  "House Flipper",
  "Ho Tu Lo Shu: The Books of Dragon",
  "Hue",
  "Hue",
  "Human: Fall Flat",
  "HUMANKIND™",
  "HUMANKIND™",
  "HUNTDOWN",
  "theHunter: Call of the Wild™",
  "theHunter: Call of the Wild™",
  "Hunting Simulator 2",
  "Hunt: Showdown",
  "Hydroneer",
  "Hyperdimension Neptunia Re;Birth1",
  "Hyperdrive Massacre",
  "Hyper Scape™",
  "Hyper Scape™",
  "ICARUS",
  "Idle Big Devil",
  "Idle Champions of the Forgotten Realms",
  "Imagine Earth",
  "Immortals Fenyx Rising™ Demo",
  "Immortals Fenyx Rising™ Demo",
  "Immortals Fenyx Rising™",
  "Immortals Fenyx Rising™",
  "The Immortal Mayor",
  "Immortal Realms: Vampire Wars",
  "Imperator: Rome",
  "I am not a Monster: First Contact",
  "The Incredible Adventures of Van Helsing: Final Cut",
  "INDUSTRIA",
  "INDUSTRIA",
  "Industries of Titan",
  "Industries of Titan",
  "Infinifactory",
  "Infliction Extended Cut",
  "Inscryption",
  "Inscryption",
  "INSOMNIA: The Ark",
  "Insurgency",
  "Insurgency: Sandstorm",
  "Into the Breach",
  "Into the Breach",
  "Ironcast",
  "Ironclad Tactics",
  "IronSight",
  "Iron Conflict",
  "Iron Harvest",
  "Iron Harvest",
  "Iron Sky: Invasion",
  "The Isle",
  "Jack Orlando: Director's Cut",
  "Jagged Alliance 2 - Wildfire",
  "Jagged Alliance - Back in Action",
  "Jurassic World Evolution™",
  "Jurassic World Evolution™",
  "Jurassic World Evolution 2",
  "Jurassic World Evolution 2",
  "Just Cause 2",
  "Just Cause™ 3",
  "Just Cause 4 Reloaded",
  "Just Cause 4 Reloaded",
  "Just Die Already",
  "Just Die Already",
  "Kathy Rain",
  "Kena: Bridge of Spirits",
  "Kenshi",
  "Kholat",
  "Killing Floor 2",
  "Killing Floor 2",
  "Kill It With Fire",
  "King's Bounty: The Legend",
  "King's Bounty: Warriors of the North",
  "King's Bounty II",
  "King's Bounty II",
  "Kingdom: Classic",
  "Kingdom: New Lands",
  "Kingdom Come: Deliverance",
  "Kingdom Come: Deliverance",
  "Kingdom: New Lands",
  "Kingdom Two Crowns",
  "THE KING OF FIGHTERS XIII",
  "The King of Fighters XIV",
  "THE KING OF FIGHTERS '98 ULTIMATE MATCH FINAL EDITION",
  "King of Seas",
  "Knights and Merchants",
  "Kona",
  "KurtzPel",
  "Labyrinth of Refrain: Coven of Dusk",
  "LARA CROFT AND THE TEMPLE OF OSIRIS™",
  "Last Epoch",
  "The Last Friend",
  "The Last Friend",
  "Last Oasis",
  "The Last Stand: Aftermath",
  "The Last Stand: Aftermath",
  "Last Tide",
  "League of Legends",
  "Left 4 Dead",
  "Left 4 Dead 2",
  "Legends of Aria",
  "Legends of Runeterra",
  "The Legend of Heroes: Trails in the Sky",
  "The Legend of Heroes: Trails in the Sky SC",
  "The Legend of Heroes: Trails in the Sky the 3rd",
  "The Legend of Heroes: Trails of Cold Steel",
  "The Legend of Heroes: Trails of Cold Steel III",
  "The Legend of Heroes: Trails of Cold Steel IV",
  "The Legend of Heroes: Trails of Cold Steel III",
  "The Legend of Heroes: Trails of Cold Steel IV",
  "Legend of Keepers",
  "Legend of Keepers",
  "Legion TD 2",
  "LEGO Builder's Journey",
  "LEGO Builder's Journey",
  "Lemnis Gate",
  "Let's Build a Zoo",
  "Let's Build a Zoo",
  "Lethal League",
  "Lethal League Blaze",
  "Liberated",
  "Life is Strange",
  "Life is Strange: Before the Storm Remastered",
  "Life is Strange Remastered",
  "Life Is Strange™ 2",
  "Life is Strange: True Colors",
  "Life is Strange - Before the Storm",
  "Little Big Workshop",
  "Lonely Mountains: Downhill",
  "The Long Dark",
  "Loop Hero",
  "Loop Hero",
  "Lords Of The Fallen™",
  "Lost At Sea",
  "Lost Castle",
  "Lost Words: Beyond the Page",
  "Lumberjack's Dynasty",
  "Magicka",
  "Magicka 2",
  "Magic the Gathering: Arena",
  "Magic the Gathering: Arena",
  "Main Assembly",
  "Maneater",
  "Maneater",
  "MapleStory",
  "March of Empires",
  "Marvel's Guardians of the Galaxy",
  "Marvel's Guardians of the Galaxy",
  "Mechwarrior 5: Mercenaries",
  "Medieval Dynasty",
  "Medieval Dynasty",
  "Medieval Engineers",
  "The Medium",
  "The Medium",
  "Men of War: Assault Squad",
  "Men of War: Assault Squad 2",
  "MetaMorph: Dungeon Creatures",
  "Metamorphosis",
  "Metin2",
  "Metro: 2033 Redux",
  "Metro: 2033 Redux",
  "Metro: Last Light Redux",
  "Metro: Last Light Redux",
  "Metro Exodus",
  "Metro Exodus",
  "Metro Exodus PC Enhanced Edition",
  "Metro Exodus Enhanced Edition - Steam",
  "Might & Magic Heroes® VI",
  "Might & Magic Heroes® VII",
  "Might & Magic Heroes® VII",
  "Might & Magic Heroes® VII - Trial by Fire",
  "Might & Magic Heroes® VII - Trial by Fire",
  "Might & Magic X Legacy",
  "Minion Masters",
  "Mini Ninjas",
  "Mirror's Edge™ Catalyst",
  "Mirror's Edge™ Catalyst",
  "Miscreated",
  "Model Builder",
  "Modern Combat 5",
  "Monopoly Madness - Ubisoft Connect",
  "MONOPOLY PLUS",
  "MONOPOLY PLUS",
  "Monster Energy Supercross - The Official Videogame 2",
  "Monster Energy Supercross - The Official Videogame 3",
  "Monster Energy Supercross - The Official Videogame 4",
  "Monster Prom",
  "Monster Sanctuary",
  "Monster Train",
  "Moonlighter",
  "Moonlighter",
  "Moons of Madness™",
  "Morbid: The Seven Acolytes",
  "MORDHAU",
  "Mordheim: City of the Damned",
  "Mortal Online 2",
  "Mortal Shell",
  "Mortal Shell",
  "Mosaic",
  "MOTHERGUNSHIP",
  "MotoGP™21",
  "MotoGP™21",
  "MotoGP™19",
  "MotoGP™ 20",
  "Mount & Blade",
  "Mount & Blade: Warband",
  "Mount & Blade: With Fire & Sword",
  "Mount & Blade II: Bannerlord",
  "Mount & Blade II: Bannerlord",
  "Move or Die",
  "Moving Out",
  "Moving Out",
  "Mr. Prepper",
  "MudRunner",
  "MudRunner",
  "MUSYNX",
  "Mutant Year Zero: Road to Eden",
  "Mutant Year Zero: Road to Eden",
  "MXGP 2019 - The Official Motocross Videogame",
  "MXGP 2020 - The Official Motocross Videogame",
  "MXGP 2021 - The Official Motocross Videogame",
  "My Memory of Us",
  "My Summer Car",
  "My Time at Portia",
  "My Time at Portia",
  "NARAKA: BLADEPOINT",
  "NARAKA: BLADEPOINT",
  "Narita Boy",
  "NASCAR Heat 3",
  "Necromunda: Hired Gun",
  "Necromunda: Hired Gun",
  "Necromunda: Underhive Wars",
  "Neon Abyss",
  "Neon Abyss",
  "Neo Cab",
  "Neptunia Virtual Stars",
  "Neverwinter",
  "New World",
  "Nex Machina",
  "Nigate Tale",
  "Night in the Woods",
  "Night of Full Moon",
  "Nine Parchments",
  "Nine to Five",
  "Northgard",
  "Not The Robots",
  "Not Tonight",
  "Not Tonight 2 - Epic Games Store",
  "Not Tonight 2 - Steam",
  "No Man's Sky",
  "Obduction",
  "Observation",
  "Observation",
  "Observer: System Redux",
  "Observer: System Redux",
  "Occupy White Walls",
  "Offworld Trading Company",
  "Old School RuneScape",
  "Old World™",
  "One Hand Clapping - Epic Games Store",
  "One Hand Clapping - Steam",
  "Onmyoji",
  "Operencia: The Stolen Sun",
  "Opus Magnum",
  "Orange Cast: Sci-Fi Space Action Game",
  "Orcs Must Die! 3",
  "Order of Battle: World War II",
  "Oriental Empires",
  "Orwell: Keeping an Eye On You",
  "Ostriv",
  "Othercide",
  "Outland",
  "Outlast",
  "Outlast 2",
  "OUTRIDERS",
  "OUTRIDERS",
  "Outward",
  "Out of Reach: Treasure Royale",
  "Overcooked",
  "Overcooked",
  "Overcooked! 2",
  "Overcooked! 2",
  "Overcooked! All You Can Eat",
  "OVERPASS™",
  "Owlboy",
  "Oxygen Not Included",
  "Pacify",
  "Paint the Town Red",
  "Paladins",
  "Paladins",
  "Panzer Corps 2",
  "Panzer Corps 2",
  "Papers, Please",
  "Paradise Killer",
  "Paradise Lost",
  "Parkasaurus",
  "Parkitect",
  "Party Hard",
  "Pascal's Wager: Definitive Edition",
  "Pathfinder: Kingmaker - Enhanced Plus Edition",
  "Pathfinder: Kingmaker - Enhanced Plus Edition",
  "Pathfinder: Wrath of the Righteous",
  "Pathfinder: Wrath of the Righteous",
  "Pathologic 2",
  "Pathway",
  "Path of Exile",
  "Path of Exile",
  "Path of Exile",
  "Path Of Wuxia",
  "Pax Nova",
  "PAYDAY 2",
  "PC Building Simulator",
  "PC Building Simulator",
  "Peaky Blinders: Mastermind",
  "The Pedestrian",
  "People Playground",
  "Per Aspera",
  "Phantom Abyss",
  "Phantom Doctrine",
  "Phasmophobia",
  "Phoenix Point: Year One Edition",
  "Pillars of Eternity",
  "Pillars of Eternity - Definitive Edition",
  "Pine",
  "PixARK",
  "A Plague Tale: Innocence",
  "Planetbase",
  "PlanetSide 2",
  "Planets Under Attack",
  "PLANET ALPHA",
  "Planet Coaster",
  "Planet Zoo",
  "Poker Club",
  "Police Simulator: Patrol Officers",
  "Portal™",
  "Portal 2",
  "Port Royale 4",
  "Port Royale 4",
  "POSTAL 2",
  "POSTAL 4: No Regerts",
  "POSTAL Redux",
  "Post Scriptum",
  "PowerWash Simulator",
  "Power Of Seasons",
  "Praetorians - HD Remaster",
  "Praey for the Gods",
  "Prison Architect",
  "Prison Architect",
  "Professional Fishing",
  "Project: Gorgon",
  "Project Highrise",
  "Project Winter",
  "Propnight",
  "Pro Cycling Manager 2017",
  "Pro Cycling Manager 2018",
  "Pro Cycling Manager 2019",
  "Pro Cycling Manager 2020",
  "Pro Cycling Manager 2021",
  "PULSAR: Lost Colony",
  "Pumpkin Jack",
  "Pure Farming 2018",
  "Q.U.B.E. 2",
  "Quest Hunter",
  "R-Type Final 2",
  "Raft",
  "RAID: World War II",
  "Railroad Corporation",
  "Railway Empire",
  "Railway Empire",
  "RAM Pressure",
  "Ratropolis",
  "Ravenfield",
  "Rayman Legends",
  "Rayman Legends",
  "Rayman Legends",
  "Rayman Origins",
  "Rayman Raving Rabbids™",
  "Rayman Raving Rabbids™",
  "Ready or Not",
  "Realm Grinder",
  "Realm Royale",
  "Recipe for Disaster",
  "Recompile",
  "Recompile",
  "Redout: Enhanced Edition",
  "Redout: Space Assault",
  "Red Wings: Aces of the Sky",
  "Reigns: Game of Thrones",
  "Remnant: From the Ashes",
  "Remnant: From the Ashes",
  "Retro Machina",
  "REZ PLZ",
  "Re:ZERO -Starting Life in Another World- The Prophecy of the Throne",
  "Rhythm Doctor",
  "Richman10",
  "Riders Republic™",
  "RIDE 3",
  "Ride 4",
  "The Riftbreaker™",
  "The Riftbreaker™",
  "RiME",
  "RiMS Racing",
  "RimWorld",
  "RimWorld",
  "Ring of Elysium",
  "Risen 2: Dark Waters",
  "Risen 3 - Titan Lords",
  "Rise of Industry",
  "Rise of the Tomb Raider: 20 Year Celebration",
  "Rise of the Tomb Raider: 20 Year Celebration",
  "Rising Storm 2: Vietnam",
  "Rising Storm 2: Vietnam",
  "Road 96",
  "Road 96",
  "Road Redemption",
  "Rocket League",
  "Rocket League",
  "Roguebook",
  "Rogue Company",
  "Rogue Heroes: Ruins of Tasos",
  "Rogue Lords",
  "Rogue Lords",
  "RollerCoaster Tycoon 3: Complete Edition",
  "RollerCoaster Tycoon 3: Complete Edition",
  "Rugby 20",
  "Ruined King: A League of Legends Story™",
  "Ruined King: A League of Legends Story™",
  "RuneScape",
  "Rune 2",
  "Russian Fishing 4",
  "Rust",
  "Rustler",
  "Sable",
  "Sable",
  "Sacred 2 Gold",
  "Sacred 3",
  "Saints Row 2",
  "Saints Row: The Third",
  "Saints Row: The Third™ Remastered",
  "Saints Row: The Third™ Remastered",
  "Saints Row IV",
  "Salt and Sanctuary",
  "Salt and Sanctuary",
  "SAMURAI SHODOWN",
  "SAMURAI SHODOWN NEOGEO COLLECTION",
  "SAMURAI SHODOWN NEOGEO COLLECTION",
  "Sanctum 2",
  "Satisfactory",
  "Satisfactory",
  "Saviors of Sapphire Wings / Stranger of Sword City Revisited",
  "Scarf",
  "Scarf",
  "Scott Pilgrim vs. The World™: The Game - Complete Edition",
  "Scott Pilgrim vs. The World™: The Game - Complete Edition",
  "ScourgeBringer",
  "SCP: Pandemic",
  "SCP: Secret Laboratory",
  "Scrap Mechanic",
  "太吾绘卷 The Scroll Of Taiwu",
  "SCUM",
  "Second Extinction™",
  "Second Extinction™",
  "Secret World Legends",
  "Semblance",
  "Serial Cleaner",
  "Session: Skateboarding Sim Game",
  "The Settlers 7: History Edition",
  "Severed Steel",
  "Shadowrun: Dragonfall - Director's Cut",
  "Shadowrun: Dragonfall - Director's Cut",
  "Shadowrun: Hong Kong - Extended Edition",
  "Shadowrun: Hong Kong - Extended Edition",
  "Shadowrun Returns",
  "Shadowrun Returns",
  "Shadow Man Remastered",
  "Shadow Man Remastered",
  "Shadow of the Tomb Raider​™ Definitive Edition",
  "Shadow of the Tomb Raider​™ Definitive Edition",
  "Shadow Warrior 3",
  "Shadow Warrior 2",
  "The Shattering",
  "Sheltered",
  "Sheltered",
  "Sheltered 2",
  "Shenmue III",
  "Shio",
  "Shiren the Wanderer: The Tower of Fortune and the Dice of Fate",
  "THE SHORE",
  "Siege Survival: Gloria Victis",
  "Siege Survival: Gloria Victis",
  "Sifu",
  "Silent Hunter III",
  "Silver Chains",
  "Skullgirls",
  "Skybolt Zack",
  "Skyborn",
  "Skyforge",
  "Skyforge",
  "Slay the Spire",
  "Sleeping Dogs™: Definitive Edition",
  "Slipways",
  "SMITE",
  "SMITE",
  "Snake Pass",
  "Sniper Elite V2 Remastered",
  "Sniper Elite 3",
  "Sniper Elite 4",
  "Sniper: Ghost Warrior 2",
  "Sniper Ghost Warrior 3",
  "Sniper Ghost Warrior Contracts",
  "Sniper Ghost Warrior Contracts 2",
  "Snooker 19",
  "SnowRunner",
  "SnowRunner",
  "SOMA",
  "SOMA",
  "Song of Iron",
  "SoulWorker",
  "South Park™: The Stick of Truth™",
  "South Park™: The Fractured But Whole™",
  "South Park™: The Fractured But Whole™",
  "South Park™: The Fractured But Whole™",
  "South Park™: The Stick of Truth™",
  "South Park™: The Stick of Truth™",
  "Spacebase Startopia",
  "Spacebase Startopia",
  "Spacelords",
  "Space Colony: Steam Edition",
  "Space Crew: Legendary Edition",
  "Space Engineers",
  "Space Haven",
  "Space Hulk: Deathwing - Enhanced Edition",
  "Space Hulk: Tactics",
  "Space Invaders Extreme™",
  "Space Rangers HD: A War Apart",
  "The Spectrum Retreat",
  "SpeedRunners",
  "Speed Brawl",
  "Spellbreak",
  "Spellbreak",
  "SpellForce - Platinum Edition",
  "SpellForce 3: Soul Harvest",
  "SpellForce 3 Reforced",
  "SpellMaster: The Saga",
  "Spintires",
  "Spirit of the North",
  "Tom Clancy's Splinter Cell Chaos Theory",
  "Splitgate",
  "SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated",
  "SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated",
  "Squad",
  "S.T.A.L.K.E.R.: Shadow of Chernobyl",
  "S.T.A.L.K.E.R.: Clear Sky",
  "S.T.A.L.K.E.R.: Call of Pripyat",
  "Starbase",
  "Starbound",
  "Stardew Valley",
  "Starmancer",
  "Starpoint Gemini Warlords",
  "Startup Company",
  "Star Control: Origins",
  "Star Renegades",
  "Star Trek Online",
  "Stationeers",
  "Stay Out",
  "Steel Division: Normandy 44",
  "Steel Division 2",
  "Steep™",
  "Steep™",
  "Steep™",
  "STEINS;GATE",
  "STEINS;GATE 0",
  "Stellaris",
  "Stick Fight: The Game",
  "Stick It to The Man!",
  "Still There",
  "Stoneshard",
  "STORY OF SEASONS: Friends of Mineral Town",
  "Stranger Things 3: The Game",
  "Strange Brigade",
  "Strategic Mind: Blitzkrieg",
  "Strategic Mind: Fight for Freedom",
  "Strategic Mind: Spectre of Communism",
  "Strategic Mind: The Pacific",
  "Streets of Rage 4",
  "Streets of Rogue",
  "Stronghold 2: Steam Edition",
  "Stronghold 3 Gold",
  "Stronghold Crusader 2",
  "Stronghold Crusader HD",
  "Stronghold HD",
  "Stronghold Kingdoms",
  "Stronghold Legends: Steam Edition",
  "Stronghold: Warlords",
  "Struggling",
  "Styx: Shards of Darkness",
  "Styx: Master of Shadows",
  "Subnautica",
  "Subnautica: Below Zero",
  "Subnautica",
  "Subnautica: Below Zero",
  "Sudden Strike 4",
  "SUPERHOT",
  "SUPERHOT: MIND CONTROL DELETE",
  "SUPERHOT: MIND CONTROL DELETE",
  "Super Animal Royale",
  "Super Magbot",
  "Super Mega Baseball 2",
  "Super Mega Baseball 3",
  "Supraland",
  "Supraland Six Inches Under",
  "Supreme Commander: Forged Alliance",
  "Supreme Commander 2",
  "Surgeon Simulator",
  "Surgeon Simulator 2",
  "The Surge",
  "The Surge 2",
  "The Survivalists",
  "Surviving Mars",
  "Surviving Mars",
  "Surviving The Aftermath",
  "Surviving The Aftermath",
  "Swords of Legends Online",
  "Swords of Legends Online",
  "Sword and Fairy",
  "Chinese Paladin: Sword and Fairy 2",
  "Sword and Fairy 7",
  "Syberia 3",
  "System Shock: Enhanced Edition",
  "Tabletop Simulator",
  "Tacoma",
  "Tacoma",
  "Tainted Grail: Conquest",
  "Tales of the Neon Sea",
  "Tales of the Neon Sea",
  "Tale of Immortal",
  "Tale of Wuxia (侠客风云传)",
  "Tale of Wuxia: The Pre-Sequel",
  "Tank Mechanic Simulator",
  "Tannenberg",
  "Tannenberg",
  "Team Fortress 2",
  "TERA",
  "Terminator: Resistance",
  "Terraria",
  "The Textorcist: The Story of Ray Bibbia",
  "Thea: The Awakening",
  "Thea 2: The Shattering",
  "They Are Billions",
  "Thief",
  "Thief™ Gold",
  "Thief: Deadly Shadows",
  "Thief Simulator",
  "This Is the Police",
  "This Is the Police 2",
  "This War of Mine: Final Cut",
  "This War of Mine: Final Cut",
  "Those Who Remain",
  "Three Kingdoms: The Last Warlord",
  "Thronebreaker: The Witcher Tales",
  "Thronebreaker: The Witcher Tales",
  "Timberborn",
  "Timberborn",
  "Titan Quest Anniversary Edition",
  "Tomb Raider",
  "Tomb Raider",
  "Tomb Raider: The Last Revelation",
  "Tomb Raider I",
  "Tomb Raider II",
  "Tomb Raider: Underworld",
  "Tom Clancy's Ghost Recon",
  "Tom Clancy's Ghost Recon: Future Soldier™",
  "Tom Clancy's Rainbow Six Lockdown™",
  "Tom Clancy's Rainbow Six Extraction",
  "Tom Clancy's Splinter Cell Conviction™",
  "Tom Clancy's Ghost Recon Breakpoint",
  "Tom Clancy's Ghost Recon Wildlands",
  "Tom Clancy's Ghost Recon Wildlands",
  "Tom Clancy's Rainbow Six Siege",
  "Tom Clancy's Rainbow Six Siege",
  "Tom Clancy's Rainbow Six Siege",
  "Tom Clancy's Splinter Cell Blacklist™",
  "Tom Clancy's Splinter Cell Blacklist™",
  "Tom Clancy's Splinter Cell Blacklist™ Deluxe Edition",
  "Tools Up!",
  "Torchlight",
  "Torchlight",
  "Torchlight III",
  "Torchlight II",
  "Torchlight II",
  "Totally Accurate Battlegrounds",
  "Totally Accurate Battle Simulator",
  "Totally Accurate Battle Simulator",
  "Totally Reliable Delivery Service",
  "Tour de France 2020",
  "Tour de France 2021",
  "Tower of Time",
  "Tower Unite",
  "Townscaper",
  "Townsmen - A Kingdom Rebuilt",
  "Trackmania",
  "Trackmania",
  "TrackMania² Stadium",
  "TrackMania² Stadium",
  "Trackmania Turbo",
  "TrackMania United Forever",
  "Trailmakers",
  "Trainz: A New Era",
  "Trainz Railroad Simulator 2019",
  "Train Fever",
  "Train Life: A Railway Simulator",
  "Train Life: A Railway Simulator",
  "Train Station Renovation",
  "Train Valley 2",
  "Transport Fever",
  "Transport Fever 2",
  "Transport Fever 2",
  "Tree of Savior",
  "Trials Fusion™",
  "Trials Rising",
  "Trials Rising",
  "Trials Rising",
  "Tricky Towers",
  "Trine Enchanted Edition",
  "Trine 2: Complete Story",
  "Trine 4: The Nightmare Prince",
  "Triton Survival",
  "Tropico 4",
  "Tropico 5",
  "Tropico 5",
  "Tropico 6",
  "Tropico 6",
  "Trover Saves The Universe",
  "Truberbrook - Epic Games Store",
  "Truberbrook - Steam",
  "TT Isle of Man Ride on the Edge",
  "TT Isle of Man Ride on the Edge 2",
  "Tunshi Kongming Legends 吞食孔明传",
  "Turnip Boy Commits Tax Evasion",
  "Two Point Hospital",
  "Tyranny",
  "Tyranny - Gold Edition",
  "UBOAT",
  "Ultimate Chicken Horse",
  "Ultimate Fishing Simulator",
  "ULTRAKILL",
  "UNDER NIGHT IN-BIRTH Exe:Late[cl-r]",
  "Unfortunate Spacemen",
  "Unity of Command II",
  "The Universim",
  "Unknown Fate",
  "UNO",
  "UNO",
  "Unravel™ Two",
  "Unravel™ Two",
  "Untitled Goose Game",
  "Untitled Goose Game",
  "Unturned",
  "V-Rally 4",
  "Valheim",
  "Valiant Hearts: The Great War™",
  "Valley",
  "Vampyr",
  "Vampyr",
  "Verdun",
  "Verdun",
  "Vesper",
  "Victoria II",
  "Vigil: The Longest Night",
  "Vikings - Wolves of Midgard",
  "Voidtrain",
  "Wanba Warriors",
  "Warface",
  "Warface",
  "Warframe",
  "Warframe",
  "Warframe",
  "Wargame: Airland Battle",
  "Wargame: European Escalation",
  "Wargame: Red Dragon",
  "Wargame: Red Dragon",
  "Wargroove",
  "Warhammer: Chaosbane",
  "Warhammer: End Times - Vermintide",
  "Warhammer: Vermintide 2",
  "Warhammer 40,000: Battlesector",
  "Warhammer 40,000: Battlesector",
  "Warhammer 40,000: Inquisitor - Martyr",
  "Warhammer 40,000: Inquisitor - Prophecy",
  "Warhammer 40,000: Mechanicus",
  "Warhammer 40,000: Gladius - Relics of War",
  "Warhammer 40,000: Gladius - Relics of War",
  "Warhammer Age of Sigmar: Storm Ground",
  "Warhammer Underworlds Online",
  "Warlock: Master of the Arcane Complete Collection",
  "Warm Snow",
  "WARNO",
  "Wartales",
  "War of Rights",
  "War Robots",
  "War Thunder",
  "War Thunder",
  "Watch_Dogs™",
  "Watch_Dogs™",
  "Watch_Dogs 2",
  "Watch_Dogs 2",
  "Watch_Dogs 2",
  "Watch Dogs: Legion",
  "Watch Dogs: Legion",
  "Welcome to the Game II",
  "Werewolf: The Apocalypse - Earthblood",
  "Werewolf: The Apocalypse - Heart of the Forest",
  "Werewolf: The Apocalypse - Earthblood",
  "West of Dead",
  "When Ski Lifts Go Wrong",
  "Where The Water Tastes Like Wine",
  "White Shadows",
  "Wildermyth",
  "The Wild Eight",
  "Will To Live Online",
  "Windbound",
  "Windbound",
  "The Wind Road",
  "The Witcher: Enhanced Edition Director's Cut",
  "The Witcher 2: Assassins of Kings Enhanced Edition",
  "The Witcher 2: Assassins of Kings Enhanced Edition",
  "The Witcher 3: Wild Hunt",
  "The Witcher 3: Wild Hunt - Game of the Year",
  "The Witcher 3: Wild Hunt - Game of the Year",
  "The Witcher Adventure Game",
  "Wolcen: Lords of Mayhem",
  "The Wonderful 101: Remastered",
  "Workers & Resources: Soviet Republic",
  "World of Tanks",
  "World of Tanks",
  "World of Tanks Blitz",
  "World of Warplanes",
  "World of Warplanes",
  "World of Warships",
  "World of Warships",
  "World of Warships",
  "World War Z: Aftermath",
  "World War Z: Aftermath",
  "Worms™ Armageddon",
  "Worms™ Clan Wars",
  "Worms™ Reloaded",
  "Worms Rumble",
  "Worms W.M.D",
  "WRC 10 FIA World Rally Championship",
  "WRC 10 FIA World Rally Championship",
  "WRC 7 FIA World Rally Championship",
  "WRC 8 FIA World Rally Championship",
  "WRC 8 FIA World Rally Championship",
  "WRC 9 FIA World Rally Championship",
  "WRC 9 FIA World Rally Championship",
  "Wreckfest",
  "Wrench",
  "Wurm Unlimited",
  "Wushu Chronicles",
  "X-Morph: Defense",
  "X3: Albion Prelude",
  "X3: Farnham's Legacy",
  "X3: Reunion",
  "X3: Terran Conflict",
  "X4: Foundations",
  "XERA: Survival",
  "XIII",
  "Xuan Yuan Sword: The Gate of Firmament",
  "Xuan-Yuan Sword VII",
  "X Rebirth",
  "Yes, Your Grace",
  "Yes, Your Grace",
  "Ylands",
  "Yoku's Island Express",
  "Yoku's Island Express",
  "Yooka-Laylee",
  "Yooka-Laylee",
  "Yooka-Laylee and the Impossible Lair",
  "Yooka-Laylee and the Impossible Lair",
  "Ys: Memories of Celceta",
  "Ys IX: Monstrum Nox",
  "Ys IX: Monstrum Nox",
  "Ys Origin",
  "Ys VIII: Lacrimosa of DANA",
  "Yuppie Psycho: Executive Edition",
  "Zanki Zero: Last Beginning",
  "Zelter",
  "Zero Escape: The Nonary Games",
  "Zero Hour",
  "Ziggurat 2",
  "Zombie Army 4",
  "Zombie Army 4",
  "Zombie Army Trilogy",
];
let prevGameNodesLength = 0;
function insertBanner() {
  //Select all game rows in steam search page
  const gameNodes = document.querySelectorAll(".search_result_row");

  gameNodes.forEach((gameNode) => {
    if (gameTitles.includes(gameNode.querySelector(".title").textContent)) {
      //Dont insert geforce button if geforceButton already inserted
      if (gameNode.querySelector(".responsive_search_name_combined > div > div > .geforce-button")) {
        return;
      } else {
        let extensionTagDiv = gameNode.querySelector(".responsive_search_name_combined > div > div");
        extensionTagDiv.innerHTML += span;
      }
    }
  });
}

//Trigger InsertBanner when new games appears on screen.
let trigger = true;
document.addEventListener("DOMNodeInserted", (event) => {
  if (trigger == true) {
    trigger = false;
    setInterval(function () {
      trigger = true;
    }, 2000);
    insertBanner();
  }
});
