const gameTitles = [
  "wolcen: lords of mayhem",
  "half-life 2",
  "far cry 3 deluxe edition",
  "thief",
  "league of legends",
  "counter-strike: global offensive",
  "assassin's creed revelations",
  "dota 2",
  "saints row: the third",
  "war thunder",
  "warframe",
  "assassin's creed iv black flag - gold edition",
  "euro truck simulator 2",
  "superhot",
  "spintires",
  "apollo 11 lunar landing demo",
  "lara croft and the temple of osiris",
  "rocket league",
  "assassin's creed iii",
  "assassin's creed: syndicate",
  "assassin's creed unity",
  "call of juarez gunslinger",
  "crossfire",
  "dayz",
  "divinity: original sin (classic)",
  "don't starve",
  "dragon age: inquisition - game of the year edition",
  "neverwinter",
  "far cry 4",
  "guild wars 2",
  "just cause 3",
  "lords of the fallen",
  "magicka 2",
  "maplestory",
  "path of exile",
  "planetside 2",
  "sniper: ghost warrior 2",
  "south park: the stick of truth™",
  "the crew",
  "world of tanks",
  "american truck simulator",
  "armored warfare",
  "black desert",
  "mount & blade: warband",
  "terraria",
  "unturned",
  "the flame in the flood",
  "far cry primal",
  "rise of the tomb raider: 20 year celebration",
  "arma 2: operation arrowhead",
  "dirty bomb",
  "don't starve together",
  "elite dangerous",
  "heroes & generals",
  "mount & blade: with fire & sword",
  "pillars of eternity",
  "prison architect",
  "rust",
  "skyforge",
  "torchlight ii",
  "wargame: airland battle",
  "warhammer: end times - vermintide",
  "x rebirth",
  "ashes of the singularity: escalation",
  "counter-strike: source",
  "divinity: original sin - enhanced edition",
  "half-life",
  "half-life 2: episode two",
  "hitman",
  "portal 2",
  "xuan yuan sword: the gate of firmament",
  "sniper elite 3",
  "tom clancy's splinter cell blacklist deluxe edition",
  "stardew valley",
  "team fortress 2",
  "tree of savior",
  "enter the gungeon",
  "tale of wuxia (侠客风云传)",
  "stellaris",
  "deliver us the moon: fortuna",
  "assetto corsa",
  "factorio",
  "mirror's edge catalyst",
  "subnautica",
  "grim dawn",
  "ark: survival evolved",
  "snake pass",
  "gwent: the witcher card game",
  "sherlock holmes: the devil's daughter",
  "hearts of iron iv",
  "zombie army trilogy",
  "nine parchments",
  "sniper elite 4",
  "dead by daylight",
  "dwarrows",
  "kenshi",
  "ys origin",
  "the legend of heroes: trails in the sky sc",
  "the legend of heroes: trails in the sky",
  "aragami",
  "watch_dogs 2",
  "outward definitive edition",
  "children of morta",
  "forts",
  "gonner",
  "brawlhalla",
  "epistory - typing chronicles",
  "serial cleaner",
  "plants vs. zombies garden warfare 2",
  "mordheim: city of the damned",
  "farming simulator 17",
  "darksiders: warmastered edition",
  "rayman legends",
  "trackmania turbo",
  "for honor",
  "steep",
  "this war of mine: final cut",
  "project zomboid",
  "fortnite",
  "crawl",
  "kholat",
  "blood bowl 2",
  "styx: master of shadows",
  "black mesa",
  "sleeping dogs: definitive edition",
  "the king of fighters xiii",
  "sanctum 2",
  "amnesia: a machine for pigs",
  "chivalry: medieval warfare",
  "paladins",
  "everspace",
  "tom clancy's the division",
  "assassin's creed: syndicate gold edition",
  "europa universalis iv",
  "legion td 2",
  "tom clancy's rainbow six siege",
  "the forest",
  "star trek online",
  "conan exiles",
  "door kickers",
  "7 days to die",
  "cities: skylines©",
  "dying light",
  "killing floor 2",
  "left 4 dead 2",
  "no man's sky",
  "payday 2",
  "shadow warrior 2",
  "smite",
  "starbound",
  "world of warships",
  "arma 3",
  "deus ex: mankind divided",
  "the witcher 3: wild hunt",
  "eve online",
  "squad",
  "starbase",
  "dead cells",
  "tom clancy's ghost recon wildlands",
  "drone swarm",
  "skyborn",
  "deathsmiles",
  "kingdom come: deliverance",
  "assassin's creed ii",
  "anno 2205",
  "hollow knight",
  "the pedestrian",
  "space engineers",
  "tabletop simulator",
  "insurgency",
  "the surge",
  "nex machina",
  "mount & blade",
  "spacelords",
  "south park: the fractured but whole™",
  "owlboy",
  "hello neighbor",
  "sniper ghost warrior 3",
  "starpoint gemini warlords",
  "battle chasers: nightwar",
  "spellforce 3 reforced",
  "the king of fighters xiv",
  "yooka-laylee",
  "trailmakers",
  "tacoma",
  "friday the 13th: the game",
  "life is strange 2",
  "mothergunship",
  "super mega baseball 2",
  "rising storm 2: vietnam",
  "garry's mod",
  "blood of steel",
  "endless space 2 - digital deluxe edition",
  "road redemption",
  "semblance",
  "divinity: original sin 2 - definitive edition",
  "rime",
  "the witcher 2: assassins of kings enhanced edition",
  "pixark",
  "vampyr",
  "tomb raider",
  "firewatch",
  "anno 2070",
  "assassin's creed: director's cut edition",
  "assassin's creed brotherhood",
  "assassin's creed rogue",
  "beyond good and evil",
  "far cry 2: fortune's edition",
  "far cry 5",
  "heroes of might & magic® iii - hd edition",
  "might & magic heroes® vii",
  "heroes of might & magic v",
  "rayman raving rabbids",
  "the crew 2",
  "distance",
  "crossout",
  "planet coaster",
  "the long dark",
  "men of war: assault squad 2",
  "absolver",
  "world of tanks blitz",
  "x-morph: defense",
  "q.u.b.e. 2",
  "black squad",
  "ark: survival of the fittest",
  "claybook",
  "mudrunner",
  "portal",
  "atomega",
  "raid: world war ii",
  "totally accurate battlegrounds",
  "citadel: forged with fire",
  "frostpunk",
  "dual universe",
  "oxygen not included",
  "assassin's creed origins",
  "jurassic world evolution",
  "cuphead",
  "depth",
  "stick fight: the game",
  "golf with your friends",
  "metro exodus",
  "besiege",
  "rimworld",
  "crusader kings ii",
  "idle champions of the forgotten realms",
  "my summer car",
  "just cause 2",
  "edge of eternity",
  "the universim",
  "counter-strike",
  "realm grinder",
  "hunt: showdown",
  "fade to silence",
  "streets of rogue",
  "beamng.drive",
  "raji: an ancient epic enhanced edition",
  "for the king",
  "three kingdoms: the last warlord",
  "atom rpg",
  "thehunter: call of the wild",
  "warhammer: vermintide 2",
  "driftland: the magic revival",
  "assassin's creed iv black flag",
  "far cry 3",
  "they are billions",
  "gtfo",
  "gravel",
  "forged battalion",
  "kingdom: classic",
  "human: fall flat",
  "bomber crew",
  "watch_dogs",
  "descenders",
  "tom clancy's splinter cell blacklist",
  "surviving mars",
  "deep rock galactic",
  "grip: combat racing",
  "pure farming 2018",
  "scum",
  "my time at portia",
  "phantom doctrine",
  "mechwarrior 5: mercenaries",
  "mount & blade ii: bannerlord",
  "magic the gathering: arena",
  "battalion 1944",
  "slay the spire",
  "battletech",
  "lonely mountains: downhill",
  "insurgency: sandstorm",
  "xera: survival",
  "into the breach",
  "hitman: absolution",
  "saints row iv",
  "mini ninjas",
  "metro: 2033 redux",
  "homefront: the revolution",
  "sacred 3",
  "metro: last light redux",
  "risen 3 - titan lords",
  "outlast",
  "tt isle of man ride on the edge",
  "aven colony",
  "wrc 7 fia world rally championship",
  "star control: origins",
  "dauntless",
  "enlisted",
  "will to live online",
  "strange brigade",
  "shadow of the tomb raider​ definitive edition",
  "yet another zombie defense hd",
  "fury unleashed",
  "deceit",
  "darwin project",
  "scp: secret laboratory",
  "astroneer",
  "unravel two",
  "dying light: bad blood",
  "fear the wolves",
  "raft",
  "darksiders ii deathinitive edition",
  "ys viii: lacrimosa of dana",
  "ravenfield",
  "pc building simulator",
  "startup company",
  "dead in vinland",
  "welcome to the game ii",
  "tower of time",
  "hitman2",
  "assetto corsa competizione",
  "biomutant",
  "mortal shell",
  "call of cthulhu",
  "darksiders iii",
  "warhammer 40,000: inquisitor - martyr",
  "blazblue: cross tag battle",
  "cultist simulator",
  "moonlighter",
  "salt and sanctuary",
  "yoku's island express",
  "realm royale",
  "crowfall",
  "just cause 4 reloaded",
  "tera",
  "shadowrun returns",
  "empyrion - galactic survival",
  "crsed: f.o.a.d.",
  "house flipper",
  "unknown fate",
  "the awesome adventures of captain spirit",
  "tropico 6",
  "assassin's creed odyssey",
  "parkasaurus",
  "wreckfest",
  "worms w.m.d",
  "hacknet",
  "miscreated",
  "iron harvest",
  "trials rising",
  "battlefleet gothic: armada 2",
  "space hulk: tactics",
  "control",
  "pathfinder: kingmaker - enhanced plus edition",
  "two point hospital",
  "overcooked! 2",
  "uno",
  "this is the police 2",
  "428: shibuya scramble",
  "post scriptum",
  "armello",
  "tricky towers",
  "papers, please",
  "russian fishing 4",
  "fate seeker",
  "necromunda: underhive wars",
  "v-rally 4",
  "danganronpa v3: killing harmony",
  "danganronpa: trigger happy havoc",
  "danganronpa 2: goodbye despair",
  "under night in-birth exe:late[cl-r]",
  "x4: foundations",
  "endless legend - emperor edition",
  "not tonight",
  "last tide",
  "soma",
  "green hell",
  "furi",
  "farming simulator 19",
  "exanima",
  "dakar 18",
  "planet alpha",
  "ultimate fishing simulator",
  "insomnia: the ark",
  "holdfast: nations at war",
  "the king of fighters '98 ultimate match final edition",
  "construction simulator 2 us - pocket edition",
  "nascar heat 3",
  "tom clancy's the division 2",
  "railway empire",
  "dungeons 3",
  "dungeon defenders ii",
  "breathedge",
  "boundless",
  "transport fever",
  "death stranding",
  "atlas",
  "dying light 2 stay human",
  "elex 2",
  "everspace 2",
  "remnant: from the ashes",
  "torchlight iii",
  "werewolf: the apocalypse - earthblood",
  "greedfall",
  "a plague tale: innocence",
  "the cycle: frontier",
  "ring of elysium",
  "i am not a monster: first contact",
  "anno 1800",
  "project winter",
  "far cry new dawn",
  "太吾绘卷 the scroll of taiwu",
  "marvel's avengers",
  "planet zoo",
  "generation zero",
  "sword and fairy 7",
  "northgard",
  "my memory of us",
  "orwell: keeping an eye on you",
  "chinese parents",
  "guilty gear xrd -revelator-",
  "amnesia: the dark descent",
  "reigns: game of thrones",
  "warhammer 40,000: mechanicus",
  "artifact",
  "ride 3",
  "deep sky derelicts",
  "farm together",
  "apex legends",
  "industries of titan",
  "disgaea 5 complete",
  "infliction extended cut",
  "lethal league blaze",
  "twin mirror",
  "outriders",
  "the architect paris",
  "maneater",
  "sable",
  "star wars jedi: fallen order",
  "the surge 2",
  "vampire the masquerade: bloodhunt",
  "second extinction",
  "the legend of heroes: trails of cold steel",
  "thief simulator",
  "dungreed",
  "mutant year zero: road to eden",
  "thronebreaker: the witcher tales",
  "musynx",
  "parkitect",
  "hobo: tough life",
  "ftl: faster than light",
  "kingdom two crowns",
  "dusk",
  "war of rights",
  "steel division 2",
  "monster energy supercross - the official videogame 2",
  "genesis alpha one deluxe edition",
  "world war z: aftermath",
  "imperator: rome",
  "amazing cultivation simulator",
  "spellbreak",
  "subnautica: below zero",
  "sins of a solar empire: rebellion",
  "foundation",
  "praey for the gods",
  "assassin's creed iii remastered",
  "warhammer: chaosbane",
  "motogp19",
  "redout: space assault",
  "zombie army 4",
  "mxgp 2019 - the official motocross videogame",
  "sniper ghost warrior contracts",
  "dawn of man",
  "dungeon defenders: awakened",
  "satisfactory",
  "the isle",
  "zanki zero: last beginning",
  "creative destruction",
  "pathway",
  "encased",
  "those who remain",
  "tyranny",
  "super animal royale",
  "mordhau",
  "supraland",
  "last epoch",
  "uboat",
  "yuppie psycho: executive edition",
  "rise of industry",
  "tales of the neon sea",
  "fell seal: arbiter's mark",
  "splitgate",
  "kurtzpel",
  "sniper elite v2 remastered",
  "kathy rain",
  "do not feed the monkeys",
  "pax nova",
  "observation",
  "age of wonders iii",
  "titan quest anniversary edition",
  "totally accurate battle simulator",
  "american fugitive",
  "hello neighbor: hide and seek",
  "trackmania² stadium",
  "session: skateboarding sim game",
  "thea 2: the shattering",
  "pathologic 2",
  "railroad corporation",
  "conan unconquered",
  "spellforce 3: soul harvest",
  "hell let loose",
  "minion masters",
  "warhammer 40,000: inquisitor - prophecy",
  "trover saves the universe",
  "tannenberg",
  "triton survival",
  "blasphemous",
  "shenmue iii",
  "blair witch",
  "tom clancy's ghost recon breakpoint",
  "watch dogs: legion",
  "age of wonders: planetfall",
  "dota underlords",
  "destiny 2",
  "gloomhaven",
  "spongebob squarepants: battle for bikini bottom - rehydrated",
  "call to arms - gates of hell: ostfront",
  "empire of sin",
  "chernobylite",
  "ai: the somnium files",
  "earth defense force 5",
  "fia european truck racing championship",
  "martha is dead",
  "darksiders: genesis",
  "silver chains",
  "deus ex: human revolution - director's cut",
  "immortals fenyx rising",
  "wrc 8 fia world rally championship",
  "moons of madness",
  "trine 4: the nightmare prince",
  "king's bounty: the legend",
  "men of war: assault squad",
  "space rangers hd: a war apart",
  "conglomerate 451",
  "king's bounty: warriors of the north",
  "redout: enhanced edition",
  "hyperdrive massacre",
  "pro cycling manager 2019",
  "vampire: the masquerade swansong",
  "wrc 9 fia world rally championship",
  "tt isle of man ride on the edge 2",
  "overpass",
  "bee simulator",
  "the bradwell conspiracy",
  "surgeon simulator",
  "cake bash",
  "recompile",
  "scourgebringer",
  "saints row 2",
  "saints row: the third remastered",
  "gods will fall",
  "sacred 2 gold",
  "chorus",
  "windbound",
  "the dark crystal: age of resistance tactics",
  "neo cab",
  "farming simulator 15",
  "blood bowl: legendary edition",
  "pro cycling manager 2018",
  "battlefleet gothic: armada",
  "styx: shards of darkness",
  "wargame: red dragon",
  "wargame: european escalation",
  "space hulk: deathwing - enhanced edition",
  "the council - episode 1",
  "train fever",
  "black future '88",
  "the eternal cylinder",
  "transport fever 2",
  "skybolt zack",
  "bridge constructor portal",
  "dead age",
  "everreach: project eden",
  "trüberbrook",
  "tropico 5",
  "commandos 2 - hd remaster",
  "sudden strike 4",
  "ride 4",
  "system shock: enhanced edition",
  "car mechanic simulator 2018",
  "wurm unlimited",
  "the escapists",
  "the escapists 2",
  "worms reloaded",
  "worms clan wars",
  "sheltered",
  "worms armageddon",
  "not the robots",
  "party hard",
  "speedrunners",
  "the final station",
  "clustertruck",
  "hellpoint",
  "the falconeer",
  "conan chop chop",
  "secret world legends",
  "the witcher: enhanced edition director's cut",
  "midnight ghost hunt",
  "goat simulator",
  "crysis remastered",
  "syberia 3",
  "ylands",
  "wargroove",
  "hotshot racing",
  "magicka",
  "crusader kings iii",
  "steel division: normandy 44",
  "hearts of iron ii: complete",
  "europa universalis iii complete",
  "victoria ii",
  "darkest hour: a hearts of iron game",
  "warlock: master of the arcane complete collection",
  "trainz: a new era",
  "star wars: squadrons",
  "pro cycling manager 2017",
  "age of conan: unchained",
  "hide and shriek",
  "cris tales",
  "lost words: beyond the page",
  "yooka-laylee and the impossible lair",
  "vikings - wolves of midgard",
  "cube world",
  "tunic",
  "the fisherman - fishing planet",
  "automation - the car company tycoon game",
  "little big workshop",
  "cyber hook",
  "days of war: definitive edition",
  "rez plz",
  "disco elysium",
  "port royale 4",
  "spacebase startopia",
  "door kickers: action squad",
  "surviving the aftermath",
  "still there",
  "terminator: resistance",
  "curious expedition 2",
  "trine enchanted edition",
  "trine 2: complete story",
  "garfield kart - furious racing",
  "asterix & obelix xxl 3 - the crystal menhir",
  "spellforce - platinum edition",
  "this is the police",
  "gothic 3",
  "jagged alliance - back in action",
  "the guild ii: renaissance",
  "blacksad: under the skin",
  "the guild 3",
  "xiii",
  "tropico 4",
  "praetorians - hd remaster",
  "the riftbreaker",
  "earth 2160",
  "enclave",
  "iron sky: invasion",
  "jagged alliance 2 - wildfire",
  "knights and merchants",
  "jack orlando: director's cut",
  "planets under attack",
  "conception plus: maidens of the twelve stars",
  "mosaic",
  "deadliest catch: the game",
  "medieval engineers",
  "battlestar galactica deadlock",
  "order of battle: world war ii",
  "warhammer 40,000: gladius - relics of war",
  "avicii invector",
  "townsmen - a kingdom rebuilt",
  "x3: reunion",
  "x3: terran conflict",
  "one hand clapping",
  "x3: albion prelude",
  "amnesia: rebirth",
  "headsnatchers",
  "oriental empires",
  "bright memory",
  "hitman 2: silent assassin",
  "hitman: blood money",
  "caliber",
  "ratropolis",
  "amid evil",
  "monster energy supercross - the official videogame 3",
  "fantasy general ii",
  "rugby 20",
  "legends of runeterra",
  "overcooked",
  "dead island definitive edition",
  "kona",
  "star renegades",
  "daemon x machina",
  "araha: curse of yieun island",
  "dcl - the game",
  "world of warplanes",
  "industria",
  "darksburg",
  "curse of the dead gods",
  "tom clancy's rainbow six extraction",
  "snowrunner",
  "hyperdimension neptunia re;birth1",
  "occupy white walls",
  "warface",
  "panzer corps 2",
  "construction simulator 2015",
  "expeditions: viking",
  "richman10",
  "stoneshard",
  "gujian3",
  "dreamscaper",
  "when ski lifts go wrong",
  "observer: system redux",
  "per aspera",
  "danganronpa another episode: ultra despair girls",
  "fire pro wrestling world",
  "steins;gate",
  "steins;gate 0",
  "zero escape: the nonary games",
  "expeditions: rome",
  "scarf",
  "hood: outlaws & legends",
  "othercide",
  "the survivalists",
  "arcana heart 3 lovemax sixstars!!!!!! xtend",
  "guilty gear xrd -sign-",
  "guilty gear xx accent core plus r",
  "dungeon defenders",
  "beat cop",
  "ao tennis 2",
  "backbone",
  "mr. prepper",
  "the legend of heroes: trails in the sky the 3rd",
  "bullet girls phantasi",
  "earth defense force 4.1 the shadow of new despair",
  "earth defense force: iron rain",
  "earth defense force 4.1 wingdiver the shooter",
  "car mechanic simulator 2015",
  "farm manager 2018",
  "tank mechanic simulator",
  "evoland legendary edition",
  "bad north: jotunn edition",
  "kingdom: new lands",
  "autonauts",
  "hue",
  "bus simulator 18",
  "fishing: barents sea",
  "war robots",
  "counter-strike: condition zero",
  "cloudpunk",
  "dreadlands",
  "hakuoki: kyoto winds",
  "roller champions",
  "elderborn",
  "super mega baseball 3",
  "snooker 19",
  "call to arms",
  "chess ultra",
  "s.t.a.l.k.e.r.: call of pripyat",
  "s.t.a.l.k.e.r.: clear sky",
  "s.t.a.l.k.e.r.: shadow of chernobyl",
  "granblue fantasy: versus",
  "pro cycling manager 2020",
  "lethal league",
  "chinese paladin: sword and fairy",
  "motogp 20",
  "last oasis",
  "onmyoji",
  "postal 2",
  "empire of angels iv",
  "postal 4: no regerts",
  "postal redux",
  "samurai shodown",
  "west of dead",
  "tomb raider: underworld",
  "tomb raider: the last revelation",
  "tomb raider ii",
  "thief: deadly shadows",
  "thief gold",
  "supreme commander 2",
  "life is strange - before the storm",
  "life is strange: true colors",
  "life is strange",
  "marvel's guardians of the galaxy",
  "dungeon siege",
  "deus ex: the fall",
  "hardspace: shipbreaker",
  "the shattering",
  "operencia: the stolen sun",
  "the wild eight",
  "evil genius 2: world domination",
  "battlezone: combat commander",
  "griftlands",
  "deadside",
  "dead island: riptide definitive edition",
  "risen 2: dark waters",
  "far cry",
  "heroes of might & magic v: tribes of the east",
  "might & magic heroes® vii - trial by fire",
  "might & magic heroes® vi",
  "main assembly",
  "xuan-yuan sword vii",
  "drug dealer simulator",
  "liberated",
  "the legend of heroes: trails of cold steel iii",
  "stronghold legends: steam edition",
  "stronghold kingdoms",
  "stronghold hd",
  "stronghold crusader hd",
  "stronghold crusader 2",
  "stronghold 3 gold",
  "space colony: steam edition",
  "metamorph: dungeon creatures",
  "stronghold: warlords",
  "stronghold 2: steam edition",
  "planetbase",
  "riders republic",
  "monopoly plus",
  "trackmania united forever",
  "assassin's creed: valhalla",
  "moving out",
  "going under",
  "king's bounty ii",
  "lost castle",
  "scrap mechanic",
  "dead age 2",
  "metin2",
  "streets of rage 4",
  "strategic mind: blitzkrieg",
  "strategic mind: the pacific",
  "huntdown",
  "atom rpg trudograd",
  "endzone - a world apart",
  "offworld trading company",
  "old world",
  "warhammer underworlds online",
  "labyrinth of refrain: coven of dusk",
  "disgaea pc",
  "disgaea 2 pc",
  "bright memory: infinite",
  "red wings: aces of the sky",
  "paradise lost",
  "metamorphosis",
  "ghostrunner",
  "wanba warriors",
  "groove coaster",
  "space invaders extreme",
  "a-train pc classic",
  "dodonpachi resurrectio",
  "bakery simulator",
  "professional fishing",
  "legend of keepers",
  "opus magnum",
  "ironclad tactics",
  "infinifactory",
  "evil genius",
  "peaky blinders: mastermind",
  "company of crime",
  "farming simulator 22",
  "trainz railroad simulator 2019",
  "the forgotten city",
  "the dungeon of naheulbeuk: the amulet of chaos",
  "paradise killer",
  "art of rally",
  "the wonderful 101: remastered",
  "gamedec",
  "dinosaur fossil hunter",
  "ram pressure",
  "workers & resources: soviet republic",
  "alan wake's american nightmare",
  "away: the survival series",
  "imagine earth",
  "endless world idle rpg",
  "avorion",
  "skullgirls",
  "stay out",
  "retro machina",
  "alchemist adventure",
  "granado espada",
  "hydroneer",
  "new world",
  "valley",
  "untitled goose game",
  "eastward",
  "galactic civilizations iii",
  "humankind",
  "day of infamy",
  "space haven",
  "ho tu lo shu: the books of dragon",
  "path of wuxia",
  "danger scavenger",
  "left 4 dead",
  "a story about my uncle",
  "yes, your grace",
  "thea: the awakening",
  "call of the sea",
  "hunting simulator 2",
  "grime",
  "labyrinthine dreams",
  "dariusburst chronicle saviours",
  "ys: memories of celceta",
  "ultrakill",
  "tour de france 2020",
  "orange cast: sci-fi space action game",
  "blightbound",
  "tale of wuxia: the pre-sequel",
  "power of seasons",
  "tunshi kongming legends 吞食孔明传",
  "the wind road",
  "shadowrun: hong kong - extended edition",
  "shadowrun: dragonfall - director's cut",
  "monster train",
  "unfortunate spacemen",
  "ultimate chicken horse",
  "gone home",
  "cardaclysm",
  "half-life 2: deathmatch",
  "pumpkin jack",
  "idle big devil",
  "sea of craft",
  "totally reliable delivery service",
  "trackmania",
  "the witcher 3: wild hunt - game of the year",
  "far cry 3: blood dragon",
  "project highrise",
  "samurai shodown neogeo collection",
  "albion online",
  "tools up!",
  "stationeers",
  "night of full moon",
  "iron conflict",
  "tomb raider i",
  "torchlight",
  "supreme commander: forged alliance",
  "lost at sea",
  "assassin's creed chronicles: china",
  "assassin's creed freedom cry",
  "assassin's creed chronicles: india",
  "assassin's creed chronicles: russia",
  "silent hunter iii",
  "the settlers 7: history edition",
  "rayman origins",
  "cyberpunk 2077",
  "stranger things 3: the game",
  "icarus",
  "hammerting",
  "ageless",
  "neon abyss",
  "monster sanctuary",
  "story of seasons: friends of mineral town",
  "shiren the wanderer: the tower of fortune and the dice of fate",
  "surgeon simulator 2",
  "desperados iii",
  "beholder 2",
  "beholder",
  "medieval dynasty",
  "arise: a simple story",
  "crown trick",
  "nine to five",
  "shadow warrior 3",
  "strategic mind: spectre of communism",
  "the medium",
  "superhot: mind control delete",
  "haven",
  "rogue company",
  "blue fire",
  "turnip boy commits tax evasion",
  "control ultimate edition",
  "mortal online 2",
  "eldest souls",
  "poker club",
  "legends of aria",
  "gunfire reborn",
  "struggling",
  "train station renovation",
  "car trader simulator",
  "god's trigger",
  "bus driver simulator",
  "among us",
  "immortal realms: vampire wars",
  "devil slayer - raksasi",
  "dicey dungeons",
  "dungeon of the endless - crystal edition",
  "ys ix: monstrum nox",
  "the legend of heroes: trails of cold steel iv",
  "disgaea 4 complete+",
  "saviors of sapphire wings / stranger of sword city revisited",
  "where the water tastes like wine",
  "zelter",
  "endless space - collection",
  "rollercoaster tycoon 3: complete edition",
  "morbid: the seven acolytes",
  "spirit of the north",
  "foreclosed",
  "stick it to the man!",
  "kill it with fire",
  "tom clancy's splinter cell chaos theory",
  "might & magic x legacy",
  "crysis 2 remastered",
  "crysis 3 remastered",
  "scott pilgrim vs. the world: the game - complete edition",
  "naraka: bladepoint",
  "dusk diver",
  "wrench",
  "dysmantle",
  "phasmophobia",
  "41 hours",
  "rune 2",
  "jurassic world evolution 2",
  "lemnis gate",
  "door kickers 2: task force north",
  "caves of qud",
  "tower unite",
  "out of reach: treasure royale",
  "werewolf: the apocalypse - heart of the forest",
  "quest hunter",
  "wushu chronicles",
  "worms rumble",
  "runescape",
  "honey, i joined a cult",
  "greak: memories of azur",
  "hokko life",
  "super magbot",
  "rogue heroes: ruins of tasos",
  "epic chef",
  "anno: mutationem",
  "gonner2",
  "space crew: legendary edition",
  "just die already",
  "outland",
  "eternal return",
  "my time at sandrock",
  "syberia: the world before",
  "r-type final 2",
  "baymax dreams of fred's glitch",
  "nigate tale",
  "ziggurat 2",
  "the textorcist: the story of ray bibbia",
  "bridge constructor: the walking dead",
  "white shadows",
  "rhythm doctor",
  "lego builder's journey",
  "pascal's wager: definitive edition",
  "f.i.s.t.: forged in shadow torch",
  "ready or not",
  "phoenix point: year one edition",
  "hitman 3",
  "sniper ghost warrior contracts 2",
  "mxgp 2020 - the official motocross videogame",
  "heroes of the three kingdoms 8",
  "the witcher adventure game",
  "immortals fenyx rising demo",
  "night in the woods",
  "townscaper",
  "story of seasons: pioneers of olive town",
  "evil dead: the game",
  "bustafellows",
  "re:zero -starting life in another world- the prophecy of the throne",
  "narita boy",
  "ruined king: a league of legends story",
  "the last friend",
  "vigil: the longest night",
  "earth defense force: world brothers",
  "aron's adventure",
  "prehistoric kingdom",
  "dyson sphere program",
  "valheim",
  "unity of command ii",
  "warhammer age of sigmar: storm ground",
  "rogue lords",
  "god of war",
  "home behind 2",
  "phantom abyss",
  "old school runescape",
  "tale of immortal",
  "rustler",
  "shio",
  "hellish quart",
  "weird west",
  "loop hero",
  "death rally",
  "alan wake",
  "the shore",
  "guilty gear -strive-",
  "absolute drift: zen edition",
  "timberborn",
  "warhammer 40,000: battlesector",
  "cybertaxi",
  "starmancer",
  "overcooked! all you can eat",
  "escape from naraka",
  "pathfinder: wrath of the righteous",
  "aragami 2",
  "hundred days",
  "neptunia virtual stars",
  "hot wheels unleashed",
  "motogp21",
  "monster energy supercross - the official videogame 4",
  "mxgp 2021 - the official motocross videogame",
  "necromunda: hired gun",
  "going medieval",
  "flashing lights - police, firefighting, emergency services simulator",
  "distant worlds 2",
  "ranch simulator",
  "anno 1404 history edition",
  "alan wake remastered",
  "gas station simulator",
  "disciples: liberation",
  "chronicon",
  "pacify",
  "deepest chamber",
  "monster prom",
  "move or die",
  "the bus",
  "ostriv",
  "scp: pandemic",
  "elex",
  "roguebook",
  "lumote: the mastermote chronicles",
  "kena: bridge of spirits",
  "trials fusion",
  "song of iron",
  "creativerse",
  "tom clancy's ghost recon: future soldier",
  "pro cycling manager 2021",
  "swords of legends online",
  "dorfromantik",
  "ghostrunner demo",
  "the incredible adventures of van helsing: final cut",
  "clid the snail",
  "cepheus protocol",
  "chinese paladin: sword and fairy 2",
  "project: gorgon",
  "sword and fairy",
  "king of seas",
  "wrc 10 fia world rally championship",
  "tour de france 2021",
  "shadow man remastered",
  "metro exodus pc enhanced edition",
  "soulworker",
  "sheltered 2",
  "child of light",
  "valiant hearts: the great war",
  "ironsight",
  "before we leave",
  "pine",
  "tom clancy's rainbow six lockdown",
  "outlast 2",
  "lumberjack's dynasty",
  "tom clancy's ghost recon",
  "tom clancy's splinter cell conviction",
  "chivalry 2",
  "march of empires",
  "modern combat 5",
  "siege survival: gloria victis",
  "x3: farnham's legacy",
  "star wars battlefront™ ii",
  "frozenheim",
  "car mechanic simulator 2021",
  "castle flipper",
  "the immortal mayor",
  "zero hour",
  "orcs must die! 3",
  "graven",
  "tainted grail: conquest",
  "faraday protocol",
  "warhammer 40,000: chaos gate - daemonhunters",
  "strategic mind: fight for freedom",
  "battlebeasts",
  "powerwash simulator",
  "leap",
  "life is strange remastered",
  "life is strange: before the storm remastered",
  "slipways",
  "black skylands",
  "battlefield v",
  "battlefield 4 premium edition",
  "battlefield 1",
  "pulsar: lost colony",
  "wildermyth",
  "the spectrum retreat",
  "death trash",
  "die after sunset",
  "death's door",
  "rims racing",
  "ironcast",
  "arid",
  "let's build a zoo",
  "banners of ruin",
  "crossfire: legion",
  "wartales",
  "core",
  "obduction",
  "space punks",
  "golf club: wasteland",
  "vesper",
  "buccaneers!",
  "check vs mate",
  "bus simulator 21",
  "recipe for disaster",
  "city of gangsters",
  "speed brawl",
  "paint the town red",
  "verdun",
  "assassin's creed iii deluxe edition",
  "road 96",
  "black book",
  "twilight wars: declassified",
  "jupiter hell",
  "voidtrain",
  "soda crisis",
  "automachef",
  "dice legacy",
  "train life: a railway simulator",
  "severed steel",
  "not tonight 2",
  "combat mission cold war",
  "beyond contact",
  "monopoly madness",
  "far cry 6",
  "age of darkness: final stand",
  "far: changing tides",
  "supraland six inches under",
  "axilon: legend of artifacts - prologue",
  "forewarned",
  "elyon",
  "the last stand: aftermath",
  "a-train: all aboard! tourism",
  "inscryption",
  "fate seeker ii (天命奇御二)",
  "highrise city",
  "propnight",
  "the crackpet show",
  "hextech mayhem: a league of legends story",
  "the anacrusis",
  "diplomacy is not an option",
  "survival quiz city",
  "fly corp",
  "rugby 22",
  "need for speed heat",
  "crowns and pawns: kingdom of deceit",
  "lost ark",
  "out there: oceans of time",
  "the king of fighters xv",
  "troubleshooter: abandoned children",
  "dune: spice wars",
  "train valley 2",
  "people playground",
  "the vanishing of ethan carter",
  "romans: age of caesar",
  "songs of conquest",
  "sifu",
  "blacksmith legends",
  "warstride challenges",
  "galactic civilizations ii: ultimate edition",
  "the political machine 2020",
  "warno",
  "blast brigade vs. the evil legion of dr. cread",
  "police simulator: patrol officers",
  "escape simulator",
  "pogostuck: rage with your friends",
  "wobbledogs",
  "backbone: prologue",
  "spellmaster: the saga",
  "model builder",
  "warm snow",
  "the riftbreaker: prologue",
  "chorus demo",
  "blood west",
  "eqi",
  "inscryption demo",
  "holomento",
  "dolmen",
  "botiboi demo",
  "seekers demo",
  "ironsmith medieval simulator",
  "hero's hour",
  "power to the people",
  "monster energy supercross - the official videogame 5",
  "dread hunger",
  "trigon: space story",
  "diplomacy is not an option demo",
  "souldiers",
  "sol cresta",
];

function home_page_constructor() {
  //create html element that will be injectted to page
  let span = "<span class='geforce-button'>GeforceNow</span>";

  function insertBanner() {
    const gameNodes = document.querySelectorAll(".tab_item_content");
    gameNodes.forEach((gameNode) => {
      const game = gameNode
        .querySelector(".tab_item_name")
        .innerText.toLowerCase()
        .replace("’", "'")
        .replace("–", "-")
        .replace("®", "")
        .replace("™", "");
      const gameAvailableOnGeforce = gameTitles.includes(game);

      if (gameAvailableOnGeforce) {
        let bannerDoesNotExist = !gameNode.querySelector(
          ".tab_item_details > .geforce-button"
        );
        if (bannerDoesNotExist) {
          let extensionTagDiv = gameNode.querySelector(".tab_item_details");
          extensionTagDiv.insertAdjacentHTML("afterbegin", span);
        }
      }
    });
  }
  function triggerInsertion() {
    //Insert at least once
    insertBanner();

    // Select the node that will be observed for mutations
    const targetNode = document.querySelector(".tabarea");

    // Options for the observer (which mutations to observe)
    const config = { attributes: true, childList: true, subtree: true };

    // Callback function to execute when mutations are observed
    const callback = function (mutationList, observer) {
      //Trigger InsertBanner when new games appears on screen.
      insertBanner();
    };
    // Create an observer instance linked to the callback function
    const observer = new MutationObserver(callback);
    // Start observing the target node for configured mutations
    observer.observe(targetNode, config);
  }
  triggerInsertion();

  return Object.freeze({
    insertBanner,
  });
}
function search_page_constructor() {
  //create html element that will be injectted to page
  let span =
    "<span class='geforce-button vr_supported' style='top:0;'>GeforceNow</span>";
  function insertBanner() {
    const gameNodes = document.querySelectorAll(".search_result_row");
    gameNodes.forEach((gameNode) => {
      const game = gameNode
        .querySelector(".title")
        .textContent.toLowerCase()
        .replace("’", "'")
        .replace("–", "-")
        .replace("®", "")
        .replace("™", "");
      if (gameTitles.includes(game)) {
        //Dont insert geforce button if geforceButton already inserted
        let bannerDoesNotExist = !gameNode.querySelector(
          ".responsive_search_name_combined > div > div > .geforce-button"
        );
        if (bannerDoesNotExist) {
          let extensionTagDiv = gameNode.querySelector(
            ".responsive_search_name_combined > div > div"
          );
          extensionTagDiv.innerHTML += span;
        }
      }
    });
  }
  function triggerInsertion() {
    // Select the node that will be observed for mutations
    const targetNode = document.getElementById("search_results");

    // Options for the observer (which mutations to observe)
    const config = { attributes: true, childList: true, subtree: true };

    // Callback function to execute when mutations are observed
    const callback = function (mutationList, observer) {
      //Trigger InsertBanner when new games appears on screen.
      insertBanner();
    };
    // Create an observer instance linked to the callback function
    const observer = new MutationObserver(callback);
    // Start observing the target node for configured mutations
    observer.observe(targetNode, config);
  }
  triggerInsertion();
  return Object.freeze({
    insertBanner,
  });
}

function game_page_constructor() {
  //create html element that will be injectted to page
  let span =
    "<span class='geforce-button vr_supported' style='top:0;'>GeforceNow</span>";
  function insertBanner() {
    const gameNode = document.getElementById("appHubAppName");
    const game = gameNode.innerText
      .toLowerCase()
      .replace("’", "'")
      .replace("–", "-")
      .replace("®", "")
      .replace("™", "");

    if (gameTitles.includes(game)) {
      //Dont insert geforce button if geforceButton already inserted
      let bannerDoesNotExist = !gameNode.querySelector(
        "#appHubAppName > .geforce-button"
      );
      if (bannerDoesNotExist) {
        gameNode.insertAdjacentHTML("beforeend", span);
      }
    }
  }

  function triggerInsertion() {
    insertBanner();
    // Select the node that will be observed for mutations
    const targetNode = document.getElementById("appHubAppName");

    // Options for the observer (which mutations to observe)
    const config = { attributes: true, childList: true, subtree: true };

    // Callback function to execute when mutations are observed
    const callback = function (mutationList, observer) {
      //Trigger InsertBanner when new games appears on screen.
      insertBanner();
    };
    // Create an observer instance linked to the callback function
    const observer = new MutationObserver(callback);
    // Start observing the target node for configured mutations
    observer.observe(targetNode, config);
  }
  triggerInsertion();
  return Object.freeze({
    insertBanner,
  });
}

function setup() {
  if (window.location.pathname === "/search/") {
    const SearchPage = search_page_constructor();
    SearchPage.insertBanner;
  } else if (
    window.location.pathname === "/" ||
    window.location.pathname.includes("/category")
  ) {
    const HomePage = home_page_constructor();
    HomePage.insertBanner;
  } else if (window.location.pathname.includes("/app")) {
    const GamePage = game_page_constructor();
    GamePage.insertBanner;
  }
}
setup();
